spring.application.name=echill-backend
# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://mysql-2cc2c868-phamhoanghuy-96f0.e.aivencloud.com:15293/echill_db?sslMode=REQUIRED&rewriteBatchedStatements=true
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_439qsgZdIKzTmluCfBg
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# dung de hien luon tham so duoc bind trong cau lenh sql duoc sinh ra
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ===============================
# PERFORMANCE TUNING (Batching)
# ===============================
spring.jpa.properties.hibernate.jdbc.batch_size=30
#giup gom gon cac batch xong roi moi thuc hien
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# ===============================
# SERVER PORT
# ===============================
server.port=8080