server:
  port: 8080

spring:
  application:
    name: echill-backend
  servlet:
    multipart:
      max-file-size: 5MB       # Giới hạn 1 file tối đa 5MB để lọt qua cửa Tomcat
      max-request-size: 10MB
  elasticsearch:
    uris: http://localhost:9200

  # ===============================
  # DATABASE CONFIGURATION
  # ===============================
  datasource:
    url: jdbc:mysql://mysql-2cc2c868-phamhoanghuy-96f0.e.aivencloud.com:15293/echill_db?sslMode=REQUIRED&rewriteBatchedStatements=true
    username: avnadmin
    password: AVNS_439qsgZdIKzTmluCfBg # ⚠️ Nhớ giấu đi khi đưa lên GitHub nhé!
    driver-class-name: com.mysql.cj.jdbc.Driver

  # ===============================
  # JPA / HIBERNATE CONFIGURATION
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 30
        order_inserts: true
        order_updates: true

  # ===============================
  # REDIS CONFIGURATION (Aiven / Valkey)
  # ===============================
  data:
    redis:
      host: valkey-dostore-phamhoanghuy-96f0.f.aivencloud.com
      port: 15294
      username: default
      password: AVNS_rmKGsDZar026KHs_sI5
      ssl:
        enabled: true

  # ===============================
  # EMAIL CONFIGURATION (Gmail SMTP)
  # ===============================
  mail:
    host: smtp.gmail.com
    port: 587
    username: echillenglish@gmail.com
    password: cojcoupjzaomoenm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# ===============================
# LOGGING CONFIGURATION
# ===============================
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE

# ===============================
# JWT CONFIGURATION
# ===============================
jwt:
  signerKey: "4666c04b12243870bf10458cb52745f79f68e7d88c1028a27cd036f37346aa96" # ⚠️ Nhớ đổi key khác khi lên Production!
  valid-duration: 7200 # in seconds (2 giờ)
  refreshable-duration: 604800 # in seconds (7 ngày)

# ===============================
# OTP CONFIGURATION
# ===============================
otp:
  prefix: ${OTP_PREFIX:otp:register:}
  expiration-minutes: ${OTP_EXPIRATION_MINUTES:5}
  resend-cooldown-seconds: ${OTP_RESEND_COOLDOWN_SECONDS:60}

# ===============================
# GOOGLE OAUTH2 CONFIGURATION
# ===============================
google:
  client-id: "38105657400-0bmvkg4d58iq8dv8vi5vl806mbfrm3ig.apps.googleusercontent.com"

# ===============================
# CLOUDINARY CONFIGURATION
# ===============================
cloudinary:
  cloud-name: dgmlgi7p4
  api-key: 628256499685731
  api-secret: uWiZf7yK-HjxcHpghszH8tzI2P0
  webhook-url: https://cleistocarpous-britany-unscabrous.ngrok-free.dev/webhook/cloudinary
